version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vladik_admin
      POSTGRES_PASSWORD: BpVh9rokOXGEUDKwo5OsJX4rqw75xa
      POSTGRES_DB: dogoroda_base
#use loc ports todo ports servers
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
